include:
  # Keyboard firmware (peripheral)
  - board: xiao_nrf52840
    shield: hhkbxplanck
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # Dongle firmware (central)
  - board: xiao_nrf52840
    shield: hhkbxplanck_dongle
